### ISSUE TITLE
JSON deserialization error: NoMemory

### ISSUE THREAD

**Issue by martcs** [egueli/SamsungM7_IR#14]
Musiccast Device Yamaha WXC-50 Samsung remote code dont recognize: [ir:UNKNOWN(68)]
Yamaha remote recognizing and showing code. But on sending vol+ or vol- get this:
"[ir:5ea1d827]VOL+ ... JSON deserialization error: NoMemory"
"[ir:RPT]VOL+ ... JSON deserialization error: NoMemory"
On display error code "Ep"
on clock button all work fine, clock showing and disappear on button press.
Can you help please ?

startup message::
 SETUP] WAIT 4...
[SETUP] WAIT 3...
[SETUP] WAIT 2...
[SETUP] WAIT 1...
services map has now 0 entries
serviceToHost map has now 0 entries
hostToAddress map has now 0 entries
Transmit NTP Request
pool.ntp.org: 162.159.200.1
Receive NTP Response
FOUND service 'viesistaba._spotify-connect._tcp.local' at host 'viesistaba.local' with address '192.168.21.100'
speaker ip valid? yes

**Comment by egueli** [comment]
Hi @martcs , first of all, thanks for using my project :)

It might be that your WXC-50 replies with a message that is a little too big than the software expects.
Try to change https://github.com/egueli/SamsungM7_IR/blob/2c9111eca6dd40e0afe61c19a8f291702af13bc2/src/speaker_musiccast.cpp#L167 from 384 to 1024 or even 2048 and try again.

Let me know if that works!

**Comment by martcs** [comment]
Hi, thanks for reply.
i try without lucky:
[ir:5ea138c7]Mute: [ir:RPT]JSON deserialization error: NoMemory
[ir:5ea158a7]VOL+ ... [ir:RPT]JSON deserialization error: NoMemory
this showing immediately. Im set 2048 . maybe this is not reply from device, showing too fast. wxc-50 is a little slow, ordinary i set a little pause between http commands, otherwise work just part of code.
what is realy GET string for musiccast? i can tray direct trought browser, and see answer.
im try find in code, but not find. i know http api, but what exactly is the queue for device?

im thinking about "setABSpeaker", wxc-50 dont have that function, return just "3" , its mean Invalid Request (A method did not exist, a method wasn’t appropriate etc. The same answer is for "getConfiguration" and "getStatus"[/YamahaExtendedControl/v1/system/getStatus]

**Comment by egueli** [comment]
I doubt it, the "JSON deserialization" happens when receiving a reply from the speaker. When sending, the device performs a serialization.
I realize that several functions specify the deserialization buffer of 384 bytes but I asked you to change only one of them. Could you replace all occurrences of `384` in `musiccast_speaker.cpp` to `2048`? There should be four occurrences.

It would be nice to know how large is response sent by your WXC-50. If you have a Mac or a Linux machine, could you run the following?
```
curl -s "http://192.168.21.100/YamahaExtendedControl/v1/main/getStatus" | wc -c
```
And tell me the number that comes out?

That command makes an HTTP request to your WXC-50. It is the same request sent by this software before changing the volume (it needs to know the current volume so it can add/remove a small amount and send the new volume). You can also use the same URL in the browser, it should show you some JSON data about the device.

**Comment by martcs** [comment]
{
  "response_code": 0,
  "power": "on",
  "sleep": 0,
  "volume": 75,
  "mute": false,
  "max_volume": 161,
  "input": "optical",
  "distribution_enable": true,
  "direct": false,
  "enhancer": true,
  "equalizer": {
    "mode": "manual",
    "low": 6,
    "mid": 2,
    "high": 3
  },
  "balance": 0,
  "subwoofer_volume": 0,
  "bass_extension": true,
  "link_control": "speed",
  "link_audio_delay": "audio_sync_on",
  "link_audio_quality": "uncompressed",
  "disable_flags": 0,
  "actual_volume": {
    "mode": "db",
    "value": -43,
    "unit": "dB"
  }
}

**Comment by martcs** [comment]
yes make change from 384 to 2048. response what im paste, get from win pc just IP+/YamahaExtendedControl/v1/main/getStatus

**Comment by martcs** [comment]
Sorry, im read again. i missunderstud. read "change in line 167" and change only line 167.  only after your last coment get "replace all occurrences". Now all work thanks. only samsung tv remote (two diferent) not work (test with yamaha remote), samsung two remotes show "unknown68", but this is issue IR library i think... thanks again work like a charm, jus need get whats wrong with samsung remote :) !

**Comment by martcs** [comment]
Hi @egueli , i found problem. Remote problem was ir library, as you wrote alowed only NEC protocol. change platformio.ini flags and problem solved. Now all work with samsung tv remote. Only on input change show "deserialization error", but this i dont use.  Thanks again for excellent project!

**Comment by egueli** [comment]
Thank you for the feedback! I fixed my code so the NoMemory error doesn't happen anymore.

Great that you fixed the Samsung remote issue. Indeed only the NEC protocol is enabled by default, because my IR receiver was very noisy and getting all sorts of IR codes if I enabled more protocols than I needed.
